name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pest:
    strategy:
      matrix:
        php-version: [ 8.1, 8.2, 8.3 ]
        platform: [ ubuntu-latest ]
      max-parallel: 20
      fail-fast: false
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: swoole
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHPStan
        run: composer analyse

      - name: Run Tests
        run: composer test
